## config file: default and user defined parameters 
distance_to_center: 50 # after homing: go to center position where cnt dispenser will vibrate
dispenser_frequency: 10 # frequency for dispensing
dispenser_duration: 100 # duration of vibration 100 ms

