## config file: default and user defined parameters 
heating_server_ip: "192.168.0.208" # 192.168.0.209 "127.0.0.1"
heating_server_port: 8881

sulfur_temperature: 120 # temperature default 120
heat_mantle1_default_set_temp : 100
heat_mantle2_default_set_temp : 100
heat_plate_default_set_temp : 160