## config file: default and user defined parameters 
ph_rotate_to_center: 10 # after homing: rotate the ph x angle to be centered
distance_to_center: 50 # after homing: go to center position where cnt dispenser will vibrate
number_of_rotation_per_direction: 10 # frequency for dispensing
reverse_direction: false # duration of vibration 100 ms
path_to_upload_img: "" #optional path for img direct load
jobid: 0					# Default to 0
jobtype: JT_PRELOAD			# Default to Preload path
res: RES_HIGH				# Default to high resolution
docwidth: 3508				# Default to A4 length @ 300dpi
ncopies: 1					# Default to 1 copy of the document
docid: 1					# Default to a document ID of 1
int scanning: 0					# Default to not scanning