## config file: default and user defined parameters 
motion_server_ip: "192.168.0.209" # 192.168.0.209 "127.0.0.1"
motion_server_port: 8882
distance_sensor_server_ip: "192.168.0.104" # 192.168.0.104 "127.0.0.1"
distance_sensor_server_port: 24687 #6555
##### first step algorithm paarmeters ######
mm_steps: 10 # distance to move down : default 10 mm
delay_to_move_request: 1000 # wait between move request : default 2000ms
##### second step algorithm parameters ######
MaxSafePos: 130 # safe max pos
ref_dis: 138 # parameter calibration sensor : default 158
##### third step algorithm parameters ######
thickness: 0.1 # thickness of wafer holder: default 0.1mm
mm_step_res: 0.01 # the lowest step resolution for axis mechanism: default 0.01 mm
wafer_travel : 100                                          # used --> # should be determined using the keyence sensor in the future
wafer_max_travel : 130                                      # used # DO NOT CHANGE IF YOU DONT KNOW WHAT YOU#RE DOING
wafer_max_speed : 800                                       # used
timeout: 10  