## config file: default and user defined parameters 
##### first step algorithm paarmeters ######
mm_steps: 50 # distance to move down : default 10 mm
delay_to_move_request: 2000 # wait between move request : default 2000ms
##### second step algorithm parameters ######
MaxSafePos: 250 # safe max pos
ref_dis: 130 # parameter calibration sensor : default 158
##### third step algorithm parameters ######
thickness: 0.1 # thickness of wafer holder: default 0.1mm
mm_step_res: 0.01 # the lowest step resolution for delta mechanism: default 0.01 mm
######### add cmake generated path variable ################
interpreter: "C:/Users/SamiDhiab/AppData/Local/Programs/Python/Python39/python.exe"
script: "C:/Users/SamiDhiab/Theion_Repos/soft_wgm_user_interface_qt_cpp/dependencies/software_wgm_v2_cpp/dependencies/soft_wafer_holder_system_controller/dependencies/software_repetier_rest_api/src/repetier_manager_lib/delta_server.py"
