name: CMake_Workflow_Push

on: [push, pull_request] 
  # This action can be manually triggered
  # workflow_call:
env:
  BUILD_TYPE: Debug
  BUILD_TARGET: ALL_BUILD # wgmApp
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  OWNER_REPO_INSTALLER: theion-batteries
  BRANCH_REPO_INSTALLER: dev_win_api

jobs:
  build_install_deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Support longpaths
        run: git config --system core.longpaths true
      - name: Fetch submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive
      - name: Printing branch name
        run: echo running on branch ${{GITHUB_REF##*/}}    
      - name: Checkout submodule branches
        run: git submodule foreach --recursive git checkout dev-win-api
      - name: Configure CMake
        env:
          CMAKE_PREFIX_PATH: ${{env.Qt6_Dir}}
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -G "Visual Studio 17 2022" -T host=x64 -A x64
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target ${{env.BUILD_TARGET}} -j 10 
      - name: pythonTests
        working-directory: ${{github.workspace}}
        run: .\pythonTests.bat 
      #- name: CTest
      #  working-directory: ${{github.workspace}}/build
      #  run: ctest -C ${{env.BUILD_TYPE}} -j10  -T test --output-on-failure
      - name: build_docs
        working-directory: ${{github.workspace}}
        run: .\generate_docs
      - name: Install
        working-directory: ${{github.workspace}}/build
        run: cmake --install . --config ${{env.BUILD_TYPE}}
      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Actions"
      - name: Setup Git
        run: |
          git config --global user.name "${{ secrets.USERNAME }}"
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global credential.https://github.com.${{ secrets.USERNAME }} ${{ secrets.GITHUB_TOKEN }}
