name: CMake_Workflow_MultiJobs

on:
  push:
    branches: [ "dev_win_api" ]
  pull_request:
    branches: [ "dev_win_api" ]
    # This action can be manually triggered
  workflow_call:
env:
  BUILD_TYPE: Debug
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Support longpaths
        run: git config --system core.longpaths true
      - name: Fetch submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive
      - name: Checkout submodule branches
        run: git submodule foreach --recursive git checkout dev_win_api

  install:
    runs-on: windows-latest
    needs: build
    steps:
      - name: vcpkg install
        run: .\vcpkg_install_script.bat

  deploy:
    runs-on: windows-latest
    needs: install
    steps:
      - name: Deploy
        run: ./deploy.sh


